@startuml uc1-sequence
skinparam sequenceMessageAlign center
actor       "General People"       as actor
boundary    UserInfoTab    as ui
control     AuthProvider  as provider
entity      DjangoServer      as server

activate ui
ui -> ui: showDialog()
activate ui
alt Cancel
    ui -> ui: Navigator.pop()
    deactivate ui

else Ok
    actor -> ui: clickOK()
    ui -> provider: deleteUser()
    activate provider
    provider -> server: DELETE api/people/delete/
    activate server
    return response
    return success
    alt success = false
        ui -> ui: showSnackBar(error: true)
    else
        ui -> ui: showSnackBar()
        ui -> ui: Navigator.pop()
    end
end
@enduml