@startuml uc1-sequence
skinparam sequenceMessageAlign center
actor       "Mobile User"       as actor
boundary    ProfilePage    as ui
control     AuthProvider  as provider
entity      DjangoServer      as server

activate  ui
ui -> ui: showModalBottomSheet()
activate ui
actor -> ui: enterOldPassword()
actor -> ui: enterNewPassword()
actor -> ui: enterConfirmPassword()
actor  -> ui: changeButton()
ui --> provider: changePassword()
activate provider
provider -> server: POST api/password/change/
activate server
return response
return success
alt success = false
    ui -> ui: showSnackbar(error: true)
end
 ui -> ui: Navigator.pop()
@enduml
