@startuml uc1-sequence
skinparam sequenceMessageAlign center
actor       "Mobile User"       as actor
boundary    AuthScreen    as ui
control     AuthProvider  as provider
entity      DjangoServer      as server

activate  ui
ui -> ui: showModalBottomSheet()
activate ui
actor -> ui: enterEmail()
actor  -> ui: resetButton()
ui --> provider: resetPassword()
activate provider
provider -> server: POST api/password/reset/
activate server
return response
return success
alt success = False
    ui -> ui: showSnackbar(Error: true)
end
@enduml
