@startuml uc1-sequence
skinparam sequenceMessageAlign center
actor       "Mobile User"       as actor
boundary    PostCreateFormScreen    as ui
control     PostCreateProvider  as provider
entity      DjangoServer      as server

activate  ui
ui -> provider: initPostRelatedTo()
activate provider
ui -> provider: initPostRelatedTo()
ui -> provider: retrieveUpdatePost()
ui -> ui: build()
activate ui
provider  -> server: GET api/post/relatedto/
activate server
provider  -> server: GET api/post/ngos/
provider  -> server: GET api/post/<post_id>/detail/
return responses
provider -> ui: success
deactivate provider
alt success = false
    ui -> ui: ErrorView()
else
    ui -> ui: PostUpdateForm(post_id, PostType.Normal)
    opt
        actor -> ui: selectRelatedTo()
        actor -> ui: enterPostContent()
        actor -> ui: pokeNGO()
        actor -> ui: togglePostAnonymous()
        actor -> ui: addPollOptions()
            actor -> ui: addPollDuration()
    end
    actor -> ui: postButton()
    ui -> ui: form.validate()
    alt validate = true
        ui -> ui: form.save()
        ui -> provider: updatePost()
        activate provider
        provider -> server: PUT api/post/<post_id>/update/
        activate server
        server --> provider: response
        deactivate server
        return success
        alt success = false
            ui -> ui: showSnackBar(error: true)
        else
            ui -> ui: showSnackBar(error: false)
            ui -> ui: Navigator.pop()
            deactivate ui
            destroy ui
        end
    end
end
@enduml
